/******************************************************************************/
/*                                                                            */
/*    $Workfile::   stdtypes.h                                           $    */
/*                                                                            */
/*    $Revision:: 2906                                                   $    */
/*                                                                            */
/*     $Archive::   P:/ArcDevLEES/RSA_CI/archives/Software/Application/HW$    */
/*                                                                            */
/*     $Modtime::   May 09 2008 11:06:40                                 $    */
/*                                                                            */
/*        $Date:: 2011-08-01 14:24:43 +0800 (周一, 01 八月 2011)     $    */
/*                                                                            */
/*      $Author:: kyleye                                                 $    */
/*                                                                            */
/*        Owner::   Team RSA                                                  */
/*                                                                            */
/*  Description::   Definition of platform independent types                  */
/*                  Do not edit this file!                                    */
/*                                                                            */
/*   Department::   B.G. Lighting Electronics                                 */
/*                                                                            */
/*                  Philips Company Confidential.                             */
/*                  Copyright (C) 2006 Koninklijke Philips Electronics N.V.   */
/*                  All rights reserved.                                      */
/*                                                                            */
/******************************************************************************/

#ifndef STDTYPES_H
#define STDTYPES_H

/******************************************************************************/
/*                            CONSTANT DEFINITIONS                            */
/******************************************************************************/

/* Suppress PC-Lint Info 755: global macro 'Symbol' (Location) not referenced
** This is a global module providing functionality that can optionally
** be used
*/

/* Suppress PC-Lint Info 506: Constant value Boolean
*/

/*lint -esym(755,BOOL,UBYTE,USHORT,ULONG,SBYTE,SSHORT,SLONG,FLOAT,DOUBLE) */
#define BOOL   B1
#define UBYTE  U8
#define USHORT U16
#define ULONG  U32
#define SBYTE  S8
#define SSHORT S16
#define SLONG  S32
#define FLOAT  F32
#define DOUBLE F64


/*lint -esym(755,FALSE,TRUE) */
/*lint -emacro(506,TRUE) */
#ifndef FALSE
#define FALSE (0)
#endif
#ifndef TRUE
#define TRUE (!0)
#endif
#ifndef DISABLE
#define DISABLE   (FALSE)
#endif
#ifndef ENABLE
#define ENABLE    (TRUE)
#endif
/*lint -esym(755,MAX_UBYTE,MIN_UBYTE) */
#define MAX_UBYTE (255)
#define MIN_UBYTE (0)

/*lint -esym(755,MAX_USHORT,MIN_USHORT) */
#define MAX_USHORT (65535)
#define MIN_USHORT (0)

/*lint -esym(755,MAX_ULONG,MIN_ULONG) */
#define MAX_ULONG (4294967295UL)
#define MIN_ULONG (0)

/*lint -esym(755,MAX_SBYTE,MIN_SBYTE) */
#define MAX_SBYTE (127)
#define MIN_SBYTE (-128)

/*lint -esym(755,MAX_SSHORT,MIN_SSHORT) */
#define MAX_SSHORT (32767)
#define MIN_SSHORT (-32768)

/*lint -esym(755,MAX_SLONG,MIN_SLONG) */
#define MAX_SLONG (2147483647L)
#define MIN_SLONG (-2147483648L)

/******************************************************************************/
/*                              MACRO DEFINITIONS                             */
/******************************************************************************/

/******************************************************************************/
/*                              TYPE DEFINITIONS                              */
/******************************************************************************/

/* Suppress PC-Lint Info 756: global typedef 'Symbol' (Location) not referenced
** Suppress PC-Lint Info 769: global enumeration constant 'Symbol' (Location)
** not referenced
** This is a global module providing functionality that can optionally
** be used
*/

/*lint -esym(756,TE_RESULT) */
/*lint -esym(769,RESULT_*) */
typedef enum
{
  RESULT_SUCCESS,
  RESULT_ERROR,
  RESULT_BAD_PARAM,
  RESULT_BAD_STATE,
  RESULT_BUSY,
  RESULT_IDLE,
  RESULT_TIMEOUT,
  RESULT_OUT_OF_RANGE,
  RESULT_UNKNOWN_PARAM,
  RESULT_BACKWARDS_EVENT
} TE_RESULT;

#define TIMER_STOPPED (0x00)
#define TIMER_EXPIRED  (0x01)

/******************************************************************************/
/*                          PUBLIC DATA DEFINITIONS                           */
/******************************************************************************/

/******************************************************************************/
/*                         PUBLIC FUNCTION PROTOTYPES                         */
/******************************************************************************/

#endif

/******************************************************************************/
/*                                 END OF FILE                                */
/******************************************************************************/
